# Generated by Django 5.1.5 on 2025-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_userfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='comments',
            field=models.ManyToManyField(blank=True, to='feeds.comment'),
        ),
    ]
