# Generated by Django 5.1.5 on 2025-01-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_userfeed_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userfeed',
            name='likes',
        ),
        migrations.AddField(
            model_name='userfeed',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feeds.tag'),
        ),
    ]
