# Generated by Django 5.1.5 on 2025-01-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_userfeed_comments_remove_userfeed_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
