# Generated by Django 5.1.5 on 2025-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_remove_post_caption_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='savedPosts',
            field=models.ManyToManyField(blank=True, to='feeds.post'),
        ),
    ]
