# Generated by Django 5.1.5 on 2025-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_userfeed_savedposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
